spring:
  application:
    name: newsService
  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

  liquibase:
    change-log: db/database_changelog-master.yaml
    enabled: true

  profiles:
    active: dev

server:
  port: 8084

logging:
  level:
    com:
      p6spy:
        engine:
          spy: DEBUG


